WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652928716 on cpu 61 ***
PC: @     0x7ff7f8805428  (unknown)  raise
    @     0x7ff7f8bab390       3872  (unknown)
    @     0x7ff79a775cb1         48  llvm::report_fatal_error()
    @     0x7ff79a707100         96  ReportErrnumFatal()
    @     0x7ff79a7072f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7ff79a70779d         48  llvm::thread::thread<>()
    @     0x7ff79a709871        144  llvm::ThreadPool::ThreadPool()
    @     0x7ff79a61f74f        496  mlir::MLIRContext::MLIRContext()
    @     0x7ff79a61fa19        160  mlir::MLIRContext::MLIRContext()
    @     0x7ff7982f50cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7ff7982e157a       4432  xla::TfrtCpuClient::Compile()
    @     0x7ff7982202b5        976  xla::PyClient::Compile()
    @     0x7ff797f8ab5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7ff797f8b434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7ff797f6c821        544  pybind11::cpp_function::dispatcher()
    @     0x556bb17dc562  110348120  _PyCFunction_FastCallDict
    @     0x556bb194c660  (unknown)  (unknown)
[2022-05-19 08:21:56,084 E 72031 78584] logging.cc:325: *** SIGABRT received at time=1652928716 on cpu 61 ***
[2022-05-19 08:21:56,085 E 72031 78584] logging.cc:325: PC: @     0x7ff7f8805428  (unknown)  raise
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff7f8bab390       3872  (unknown)
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff79a775cb1         48  llvm::report_fatal_error()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff79a707100         96  ReportErrnumFatal()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff79a7072f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff79a70779d         48  llvm::thread::thread<>()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff79a709871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff79a61f74f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff79a61fa19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff7982f50cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff7982e157a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff7982202b5        976  xla::PyClient::Compile()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff797f8ab5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff797f8b434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x7ff797f6c821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:21:56,087 E 72031 78584] logging.cc:325:     @     0x556bb17dc562  110348120  _PyCFunction_FastCallDict
[2022-05-19 08:21:56,090 E 72031 78584] logging.cc:325:     @     0x556bb194c660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 126 in sign
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 559 in sign
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/utils/comboptnet_utils.py", line 43 in compute_delta_y
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 222 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
4.97user 1.42system 0:23.31elapsed 27%CPU (0avgtext+0avgdata 1992768maxresident)k
1888inputs+48outputs (0major+304317minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652929027 on cpu 8 ***
PC: @     0x7f8974fc8428  (unknown)  raise
    @     0x7f897536e390       3872  (unknown)
    @     0x7f8916f38cb1         48  llvm::report_fatal_error()
    @     0x7f8916eca100         96  ReportErrnumFatal()
    @     0x7f8916eca2f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7f8916eca79d         48  llvm::thread::thread<>()
    @     0x7f8916ecc871        144  llvm::ThreadPool::ThreadPool()
    @     0x7f8916de274f        496  mlir::MLIRContext::MLIRContext()
    @     0x7f8916de2a19        160  mlir::MLIRContext::MLIRContext()
    @     0x7f8914ab80cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7f8914aa457a       4432  xla::TfrtCpuClient::Compile()
    @     0x7f89149e32b5        976  xla::PyClient::Compile()
    @     0x7f891474db5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7f891474e434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7f891472f821        544  pybind11::cpp_function::dispatcher()
    @     0x55bf4ddf2562  (unknown)  _PyCFunction_FastCallDict
    @     0x55bf4df62660  (unknown)  (unknown)
[2022-05-19 08:27:07,774 E 100469 111694] logging.cc:325: *** SIGABRT received at time=1652929027 on cpu 8 ***
[2022-05-19 08:27:07,774 E 100469 111694] logging.cc:325: PC: @     0x7f8974fc8428  (unknown)  raise
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f897536e390       3872  (unknown)
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8916f38cb1         48  llvm::report_fatal_error()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8916eca100         96  ReportErrnumFatal()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8916eca2f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8916eca79d         48  llvm::thread::thread<>()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8916ecc871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8916de274f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8916de2a19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8914ab80cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f8914aa457a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f89149e32b5        976  xla::PyClient::Compile()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f891474db5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f891474e434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x7f891472f821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:27:07,777 E 100469 111694] logging.cc:325:     @     0x55bf4ddf2562  (unknown)  _PyCFunction_FastCallDict
[2022-05-19 08:27:07,781 E 100469 111694] logging.cc:325:     @     0x55bf4df62660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 455 in _convert_element_type
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 272 in <listcomp>
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 272 in _promote_dtypes
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 326 in _promote_args
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 421 in <lambda>
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 5873 in <lambda>
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 5869 in deferring_binary_op
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 232 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
6.88user 1.83system 0:26.94elapsed 32%CPU (0avgtext+0avgdata 1994740maxresident)k
0inputs+48outputs (0major+317533minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
